name: Lab1

on: [push]

jobs:
    python-version:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.9
              uses: actions/setup-python@v4
              with:
                python-version: 3.9
            - name: Display Python version
              run: python -c "import sys; print(sys.version)"

    test-pylint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.9
              uses: actions/setup-python@v4
              with:
                python-version: 3.9
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install pylint
            - name: Analysing the code with pylint
              run: |
                find . -name '*.py' -exec pylint {} \;